---
title: "Beereport"
output:
  html_document: default
  html_notebook: default
---

```{r}
library (dismo); library(raster);library(rgdal);library (sp);
library (maptools); library (mgcv); library (gbm)
```

```{r}
#cleaning bee data
library(tidyverse)
library(raster)
bees<- read.csv("bombus_bor.csv", header = FALSE)
head(bees)
glimpse(bees)
bees[2:nrow(bees), ]
beeloc<-bees[, 5:6]
collabs<-c("decimallat", "decimallong", "year")
#getting rid of gross columns
beesclean<-filter(bees, V11 == "1340373")
beedata<-beesclean[c(5:6, 10)]
names(beedata)<-collabs
head(beedata)

```

```{r}
#remove duplicate observations
duplicated(beedata)
beedata2<-beedata[!duplicated(beedata), ]
duplicated(beedata2)
```

```{r}
#plotdata
library(maptools)
data("wrld_simpl")
beedata2$decimallat<-as.numeric(as.character(beedata2$decimallat))
beedata2$year<-as.numeric(as.character(beedata2$year))
plot(wrld_simpl, xlim=c(-150, -50), ylim=c(30, 70), axes=T, col="lightgrey")
points( x = beedata2$decimallong, y = beedata2$decimallat, col="red", pch=16)
str (beedata2)
summary (beedata2)
oldbees<-filter(beedata2, year < 2000, year >= 1940, decimallat >= 45 | decimallong >= -100 )
newbees<-filter(beedata2, year > 2000)
```


```{r}
#plotting old bees
plot(wrld_simpl, xlim=c(-150, -50), ylim=c(30,70), axes=T, col="lightgrey")
points( x = oldbees$decimallong, y = oldbees$decimallat, col="red", pch=16)

```

```{r}
#plotting new bees
plot(wrld_simpl, xlim=c(-150, -50), ylim=c(30,70), axes=T, col="lightgrey")
points(x = newbees$decimallong, y = newbees$decimallat, col="red", pch=16)
```

```{r}
#loading in rasters
temp<-raster ("bio1.bil")
precip<- raster ("bio12.bil")
precip_wq<- raster ("bio13.bil")
temp_wq<- raster("bio10.bil")

predictors<-stack ( temp, precip, precip_wq, temp_wq)

#crop the stack 
predictors_crop<- crop (predictors,  extent(-150, -50, 30, 70))
plot (predictors_crop)

# we use the first file to create a RasterLayer
plot(predictors_crop[[1]]) 
mask <- raster(predictors_crop[[1]])
mask


```
```{r}
# select 500 random points
# set seed to assure that the examples will always have the same random sample.
set.seed(2000)
bg <- randomPoints(mask, 500 )
head (bg)
str (bg)

```

```{r}
# set up the plotting area
plot(!is.na(mask), legend=FALSE)
points(bg, cex=0.5)
# now we repeat the sampling, but limit
# the area of sampling using a spatial extent
e <- extent(-150, -50, 30, 70)
bg2 <- randomPoints(mask, 50, ext=e)
plot(!is.na(mask), legend=FALSE)
plot(e, add=TRUE, col="red")
points(bg2, cex=0.5)


plot (wrld_simpl, xlim=c(-180, -50), ylim=c(23,90), axes=T, col="lightgrey")
points (data=xy, x=oldbees$decimallong, y=oldbees$decimallat, col="red", pch=16, cex=.5)
points (bg, pch=16, col="blue", cex=.25)
```
```{r}
#We can now use the extract function as we did before to mine data from each of these geographic locations: 
#presences
str(predictors_crop)
?extract
head(presvals)
presvals <- extract(predictors_crop, oldbees[, c(2,1)])
presvals <- na.omit (presvals) #gets rid of any observations with no data 
#psuedo-absences
absvals <- extract(predictors_crop, bg)
absvals <- na.omit (absvals) #gets rid of any observations with no data 
head(absvals)
#combine presences and absences into a single dataframe 
pb <- c(rep(1, nrow(presvals)), rep(0, nrow(absvals)))
sdmdata <- data.frame(cbind(pb, rbind(presvals, absvals)))
head(sdmdata)

#investigate co-linearity: Are these predictors telling us the same thing? 
pairs (sdmdata [,2:5], cex=.25, fig=TRUE)

```

```{r}
#When two variables are strongly correlated it is best to run the model with only one of them, unless you have a strong biological reason to not do this 

#now our dataset is readly lets fit our first model (Chapter 5 in SDM)
#lets start with a simple Generalized Linear Model (glm)
m1 <- glm(pb ~ bio1 + bio13 + bio10, data=sdmdata)
summary (m1)
response(m1)

#with our model built we can now predict to the entire study extent: 
glm_pred<- predict (predictors_crop, m1)
plot (glm_pred, col=rev(rainbow(50)), main="GLM")# This now plots the habitat suitability for this species 

#evaluate the model 
mE1 <- evaluate(xy, bg, x= predictors_crop , m1)
mE1

#Apply a threshold to convert to a binary map:
?threshold
tr <- threshold(mE1,'spec_sens')
tr
current_pa<- (glm_pred > tr)
plot(glm_pred > tr, main='presence/absence')
#how does this map change if we change the threshold type from spec_sens to the other thresholds? 

#lets now construct a generalized additive model (gam)
library (mgcv)
m2<-gam(pb ~ bio1 * bio13 + bio10 , data=sdmdata)
summary (m2)
response(m2)
gam_pred<- predict (predictors_crop, m2)
plot (gam_pred, col=rev(rainbow(50)), main="GAM") 
```

```{r}
#Begin Lab 5 here: 
#project our models to a future climate 
#load in rasters and stack them: 
#Important to make sure the files in your future stack are the named the same as your predictor variables 
bio1f<-raster ("bio1.tif")
bio12f<- raster("bio12.tif")
bio13f<- raster("bio13.tif")
#bio7f<- raster("bio7.tif")

future_stack<-stack (bio1f, bio12f, bio13f)
plot (future_stack)

#lets clip it to our study extent: 
future_crop<- crop (future_stack,  extent(-150, -50, 30, 70))
plot (future_crop)

#now all we do is project our models (m1 and m2) to the future stack! 
summary (m1)
summary (m2)

glm_future<- predict (future_crop, m1)

#you can also apply teh threshold as you before to create a presence absence map 
glm_future_bi<-glm_future > tr
plot (glm_future_bi)

#now plot them

par(mfrow=c(2,2)) 
plot (glm_pred, main="2017 Distribution")
plot (glm_future, main="2070 RCP 8.5")

#using raster math we can calculate the differences between the two maps 
diff_map<- glm_future-glm_pred
plot (diff_map, col=heat.colors(100), main="Difference Map")

diff_pa_map<- glm_future_bi - current_pa
plot (diff_pa_map, col=heat.colors(100), main="Difference Map P/A")

```


